export const ProductData = [
  {
    id: 1,
    name: "Lenovo Thinkpad T490S",
    image: "/images/laptop.jpg",
    newPrice: "250000",
    oldPrice: "300000",
    discount: "2",
    description: "Block out distractions and enjoy immersive work with these comfortable Laptops. Perfect for travel, work, or simply enjoying your music.",
    tag: "Electronics",
  },
  {
    id: 2,
    name: "Colorless T-Shirts (Lightweight)",
    image: "/images/tshirts.jpg",
    newPrice: "120000",
    oldPrice: "150000",
    discount: "2",
    description: "These lightweight and breathable running shirts are designed for optimal performance during your runs. Experience comfort and support with every stride.",
    tag: "Sports & Fitness",
  },
  {
    id: 3,
    name: "Sumsung Galaxy",
    image: "/images/phone.jpg",
    newPrice: "250000",
    oldPrice: null, // No old price if not applicable
    discount: "0",
    description: "Enjoy every dream of your phone. A sustainable choice for everyday use.",
    tag: "Phones And Accessories",
  },
  {
    id: 4,
    name: "Hisense 60L Fridge",
    image: "/images/fridge.jpg",
    newPrice: "40000",
    oldPrice: null,
    discount: "0",
    description: "Challenge your friends and family with this amazing fridge. Perfect for business or home.",
    tag: "Kitchen And Dining",
  },
  {
    id: 5,
    name: "Bedroom Items (Spacious)",
    image: "/images/matress.jpg",
    newPrice: "80000",
    oldPrice: "100000",
    discount: "2",
    description: "Pack everything you need for your next adventure with this spacious and comfortable beddings. Features multiple compartments for organized packing.",
    tag: "Bedroom",
  },
  {
    id: 6,
    name: "Lined Notebook",
    image: "/images/speaker.jpg",
    newPrice: "10000",
    oldPrice: null,
    discount: "0",
    description: "Capture your ideas, thoughts, and notes in this high-quality lined notebook. Perfect for students, professionals, or anyone who loves to write.",
    tag: "Office Supplies",
  },
  {
    id: 7,
    name: "Living Room Seats",
    image: "/images/sofar.jpg",
    newPrice: "30000",
    oldPrice: null,
    discount: "0",
    description: "Made with soft, sustainable organic cotton, this t-shirt is perfect for everyday wear. Eco-friendly and comfortable for all-day use.",
    tag: "Home",
  },
  {
    id: 8,
    name: "Indoor Plant (Easy Care)",
    image: "/images/speaker.jpg",
    newPrice: "20000",
    oldPrice: null,
    discount: "0",
    description: "Bring some life to your home with this beautiful and easy-care indoor plant. Requires minimal maintenance, perfect for busy lifestyles.",
    tag: "Home & Garden",
  },
  {
    id: 9,
    name: "Home Theatre",
    image: "/images/speaker.jpg",
    newPrice: "250000",
    oldPrice: null,
    discount: "0",
    description: "Enjoy the cool music at your comfort.",
    tag: "Electronics",
  },
  {
    id: 10,
    name: "Basic Tool Kit",
    image: "/images/speaker.jpg",
    newPrice: "5000",
    oldPrice: "30000",
    discount: "2",
    description: "Block out distractions and enjoy immersive audio with these comfortable wireless headphones. Perfect for travel, work, or simply enjoying your music.",
    tag: "Electronics",
  }]
