export const ServicesData = [
  {
    name: "Aman Resorts Hotel",
    image: "/images/serviceimg12.jpg",
    location: "Kitagobwa, Kampala",
    rated: "4.5",
    rating: "2,956",
    tag: "Hotel",
  },
  {
    name: "Mountain Air Massage",
    image: "/images/serviceimg2.jpg",
    location: "Munyonyo, Kampala",
    rated: "4.9",
    rating: "2,356",
    tag: "Massage",
  },
  {
    name: "Power Squad Fitness",
    image: "/images/serviceimg3.jpg",
    location: "Wantone, Mukono",
    rated: "4.5",
    rating: "1,438",
    tag: "Gym",
  },
  {
    name: "Hidden Gem Salon",
    image: "/images/serviceimg4.jpg",
    location: "Mbuya, Kampala",
    rated: "4.9",
    rating: "3,546",
    tag: "Salon",
  },
  {
    name: "Breeze Blows Salon",
    image: "/images/serviceimg5.jpg",
    location: "Naalya, Kampala",
    rated: "4.8",
    rating: "2,463",
    tag: "Salon",
  },
  {
    name: "Body Works Gym",
    image: "/images/serviceimg6.jpg",
    location: "Kawempe, Kampala",
    rated: "4.2",
    rating: "463",
    tag: "Gym",
  },
  {
    name: "Release Massage Therapy",
    image: "/images/serviceimg7.jpg",
    location: "Kasubi, Kampala",
    rated: "4.6",
    rating: "1,483",
    tag: "Massage",
  },
  {
    name: "Breeze Blows Salon",
    image: "/images/serviceimg8.jpg",
    location: "Makindye, Kampala",
    rated: "4.7",
    rating: "1,453",
    tag: "Salon",
  },
  {
    name: "Whale Cave Inn Hotel",
    image: "/images/serviceimg9.jpg",
    location: "Kajansi, Entebbe",
    rated: "4.8",
    rating: "2,453",
    tag: "Hotel",
  },
  {
    name: "Blue Moon Hotel",
    image: "/images/serviceimg10.jpg",
    location: "Naalya, Kampala",
    rated: "4.6",
    rating: "1,553",
    tag: "Hotel",
  },
  {
    name: "El Rancho Casino Hotel",
    image: "/images/serviceimg11.jpg",
    location: "Munyonyo, Kampala",
    rated: "4.8",
    rating: "2,553",
    tag: "Hotel",
  },
  {
    name: "Rising Sun Massage Therapy",
    image: "/images/serviceimg1.jpg",
    location: "Makindye, Kampala",
    rated: "4.9",
    rating: "1,456",
    tag: "Massage",
  },
  {
    name: "Hair Poetry Salon",
    image: "/images/serviceimg4.jpg",
    location: "Kitagobwa, Kampala",
    rated: "4.5",
    rating: "2,956",
    tag: "Salon",
  },
];
